// functions/_lib/connectors/dummy.js
// =========================================================================
// Dummy connector (Block 3, decisions L, M, N).
//
// Zero-auth synthetic connector. Validates the framework end-to-end
// before Block 4 wires the first real connector (Slack). Once Block 3
// closes, the dummy stays in the registry as a permanent
// integration-test surface — useful for re-verifying the connector
// framework when a future block touches the encryption helper, the
// connections HTTP API, or the entity upsert path.
//
// AUTH MODEL (decision L)
// -----------------------
// authKind = 'none'. startAuth returns empty credentials immediately;
// completeAuth no-ops auth and returns a synthetic accountInfo;
// refreshAuth is a pass-through.
//
// testConnection EXERCISES THE CRYPTO ROUND-TRIP. It calls
// decrypt(ctx.env, connection, aadFor(connection)) on the stored row
// and asserts the plaintext equals '{}' (the JSON-encoded form of
// the empty credentials object). This proves encrypt/decrypt/AAD are
// wired up correctly without needing real credentials. Decision L
// explicitly rejects the "return bare {ok: true}" shortcut here —
// the dummy's whole job is to validate the framework, and the crypto
// round-trip is part of the framework.
//
// METADATA (decision M)
// ---------------------
// external_account_id is generated by completeAuth as
// `dummy-${randomUUID().slice(0, 12)}`. The handler stores
// accountInfo.id as the connection's external_account_id, so
// multiple dummy connects to the same project don't collide on the
// schema's UNIQUE constraint.
//
// SYNC PAYLOAD (decision N)
// -------------------------
// fullSync UPSERTs three hardcoded fixture entities directly via
// ctx.sql, returning the records_inserted vs records_updated split.
// Idempotency comes from the schema's
// UNIQUE (connection_id, source_type, source_id) — re-syncing
// updates rather than duplicates. The xmax = 0 trick distinguishes
// inserts from updates in the RETURNING clause.
// incrementalSync delegates to fullSync (no cursor semantics for
// the dummy fixtures).
// =========================================================================

import { aadFor, decrypt } from '../crypto.js';

/** @type {import('./types.js').ConnectorMetadata} */
const METADATA = {
  source: 'dummy',
  displayName: 'Dummy Connector',
  authKind: 'none',
  description:
    'Synthetic connector that syncs three fixture entities. Used for framework validation; not a real data source.',
};

const FIXTURE_ENTITIES = [
  {
    source_type: 'dummy_item',
    source_id: 'dummy-1',
    title: 'Dummy item 1',
    content_text: 'Fixture content for the first dummy entity.',
    metadata: { tag: 'fixture', index: 1 },
    source_url: 'https://example.com/dummy/1',
  },
  {
    source_type: 'dummy_item',
    source_id: 'dummy-2',
    title: 'Dummy item 2',
    content_text: 'Fixture content for the second dummy entity.',
    metadata: { tag: 'fixture', index: 2 },
    source_url: 'https://example.com/dummy/2',
  },
  {
    source_type: 'dummy_item',
    source_id: 'dummy-3',
    title: 'Dummy item 3',
    content_text: 'Fixture content for the third dummy entity.',
    metadata: { tag: 'fixture', index: 3 },
    source_url: 'https://example.com/dummy/3',
  },
];

// Plaintext credentials are an empty JSON object — `{}`. The dummy
// has no real secret; we still encrypt this empty payload so the
// crypto path runs on every connect (and the testConnection
// round-trip has something to verify).
const DUMMY_PLAINTEXT_CREDENTIALS = '{}';

/** @type {import('./types.js').Connector} */
export const dummy = {
  getMetadata() {
    return METADATA;
  },

  // No OAuth: returns the credential payload immediately. The handler
  // will pass this through to completeAuth in the same request.
  async startAuth(_ctx) {
    return { credentials: {} };
  },

  // Generates the synthetic external_account_id. Per decision M, this
  // is `dummy-${randomUUID().slice(0, 12)}` so multiple dummy connects
  // to the same project don't collide on the connections UNIQUE
  // constraint (NULLS NOT DISTINCT on
  // (project_id, source, external_account_id, deleted_at)).
  async completeAuth(_ctx, _params) {
    return {
      credentials: {},
      accountInfo: {
        id: `dummy-${crypto.randomUUID().slice(0, 12)}`,
      },
    };
  },

  // No refresh semantics for dummy.
  async refreshAuth(_ctx, credentials) {
    return credentials;
  },

  // Decision L: actually exercise the crypto round-trip on the stored
  // row. A bare `{ ok: true }` would not validate the framework.
  async testConnection(ctx, connection) {
    const aad = aadFor(connection);
    const plaintext = await decrypt(ctx.env, connection, aad);
    if (plaintext !== DUMMY_PLAINTEXT_CREDENTIALS) {
      // SECURITY — for future connector authors copying this pattern:
      // do NOT include any portion of decrypted plaintext in the error
      // message, even truncated. The dummy's plaintext is harmless
      // (`{}`), but Slack/Jira/Drive connectors copying this code
      // would have real OAuth tokens or API keys in `plaintext` —
      // logging any prefix of those into Cloudflare's request logs
      // is a credential leak. The error string must be value-free
      // (expected and actual both implicit), and any debugging detail
      // a connector wants to add must be derivable WITHOUT the
      // plaintext value (e.g., `plaintext.length === 0` is fine,
      // `plaintext.slice(0, N)` is not).
      throw new Error(
        'dummy.testConnection: decrypted credentials do not match expected empty payload'
      );
    }
    return { ok: true };
  },

  // UPSERT three fixture rows. The handler is responsible for opening
  // ctx.sql and creating/updating the surrounding sync_runs row;
  // fullSync owns the entities table writes.
  async fullSync(ctx, connection) {
    const sql = ctx.sql;
    let inserted = 0;
    let updated = 0;

    for (const e of FIXTURE_ENTITIES) {
      const [row] = await sql`
        INSERT INTO entities (
          project_id, connection_id, source, source_type, source_id,
          title, content_text, metadata, source_url
        ) VALUES (
          ${connection.project_id}, ${connection.id}, ${'dummy'},
          ${e.source_type}, ${e.source_id},
          ${e.title}, ${e.content_text}, ${e.metadata}, ${e.source_url}
        )
        ON CONFLICT (connection_id, source_type, source_id) DO UPDATE
        SET title         = EXCLUDED.title,
            content_text  = EXCLUDED.content_text,
            metadata      = EXCLUDED.metadata,
            source_url    = EXCLUDED.source_url,
            updated_at    = NOW()
        RETURNING (xmax = 0) AS inserted
      `;
      if (row.inserted) inserted++;
      else updated++;
    }

    return {
      records_inserted: inserted,
      records_updated: updated,
      records_skipped: 0,
    };
  },

  // No cursor semantics; delegate to fullSync.
  async incrementalSync(ctx, connection) {
    return dummy.fullSync(ctx, connection);
  },

  // No webhooks for dummy. The optional handleWebhook field is
  // omitted entirely (per the typedef's [optional] marker).
};

/**
 * Internal export of the fixture data, for tests and verification
 * scripts that want to compare expected vs actual entity content
 * without invoking fullSync. Not part of the Connector interface.
 */
export const DUMMY_FIXTURE_ENTITIES = FIXTURE_ENTITIES;
