// functions/_lib/connectors/jira.js
// =========================================================================
// SECURITY-CARVE-OUT: do not edit in auto mode
//
// Jira connector. Implements decisions A (API token, no OAuth),
// B (5 REST endpoints; commit 2 only uses /myself), C (envelope
// encryption reuse), D (single project per connection — picker in
// commit 9), E + E1 + E2 + E3 (sync model — commits 5/6 only;
// commit 2 ships stubs that return inert SyncResult), F (single
// connection per Jira instance per project — enforced at the save
// endpoint in commit 3, not here), G (project listing endpoint —
// commit 4), H (entity mapping — commits 5/6), I/I1/I2/I3/I4 (tools
// — commit 7), J (jira_issues view — commit 4), K (system prompt —
// commit 8), L (connect UI — commit 9), N (bespoke save endpoint —
// commit 3), O (cursor format — commit 6) from BLOCK_6_PLAN.md.
//
// AUTH MODEL (decision A)
// -----------------------
// authKind = 'token'. Per-user Atlassian API token, generated by the
// admin at https://id.atlassian.com/manage-profile/security/api-tokens.
// Authentication on outbound calls is HTTP Basic:
//   Authorization: Basic ${base64(email + ':' + apiToken)}
// No OAuth callback, no refresh tokens, no consent screen. Connections
// are created via POST /api/connectors/jira/auth/save (decision N),
// which calls completeAuth directly. startAuth throws to satisfy the
// Connector interface contract — it should never be reached for Jira.
//
// CREDENTIAL SHAPE
// ----------------
// Encrypted blob: { site_url, account_email, api_token } as JSON.
// credential_metadata (non-secret, dashboard-visible to admins):
//   { site_url, account_email, atlassian_account_id,
//     selected_project_key?, selected_project_name? }
// Note credential_metadata MUST NOT contain api_token (verified by
// S21 in the verification matrix).
//
// EXTERNAL_ACCOUNT_ID (decision C, fallback path)
// -----------------------------------------------
// connections.external_account_id stores the lowercased site host
// (e.g. 'mycompany.atlassian.net'). Decision C originally preferred
// the Atlassian site cloud ID from /_edge/tenant_info, but v1.1 takes
// the simpler fallback path: lowercased site host is unambiguous,
// requires zero extra API calls, and satisfies decision F's UNIQUE-
// constraint slot for "single connection per Jira instance per
// project." Block 9 polish: switch to cloud ID if multi-region or
// vanity-domain instances surface.
//
// SECURITY (mirrors slack.js)
// ---------------------------
// Error strings MUST NOT include any byte of the plaintext API token,
// not even truncated. Atlassian's error responses on 401/403 don't
// echo the token, so jiraGet's response body snippet is safe to log;
// validation errors don't include the token either. NEVER concatenate
// creds.api_token into any error or log line.
//
// COMMITS 5/6 ADDITIONS (deferred from commit 2)
// ----------------------------------------------
// fullSync, incrementalSync — currently stubbed to return inert
// SyncResult ({inert:true, reason:'not implemented yet'}). The L
// inert-sync rule (Block 4) means /sync calls against Jira
// connections in the commit-2-through-commit-4 window won't poison
// connections.last_sync_at. Real implementations land in commits 5
// (fullSync via /rest/api/3/search + agile API) and 6 (incremental
// via JQL `updated >= last_sync_cursor`).
//
// E3 NO WEBHOOK FOR V1.1
// ----------------------
// Jira webhooks require admin-level configuration in the Atlassian
// instance settings (per-instance, not per-user). API-token-auth
// users cannot register webhooks programmatically. v1.1 ships
// without handleWebhook; admin uses the manual "Sync now" button +
// Block 9's nightly cron. Per decision E3.
// =========================================================================

import { aadFor, decrypt } from '../crypto.js';
import { EMBEDDING_MODEL_ID } from '../ai/embeddings.js';
import { embedEntityRow, writeEntityWithEmbedding } from './_shared/entity_writer.js';

const ATLASSIAN_API_VERSION = '3';
const ATLASSIAN_AGILE_API_VERSION = '1.0';
const ATLASSIAN_USER_AGENT = 'elinno-agent/1.1';

// Standard Atlassian Cloud custom field IDs. Verified at commit 5
// coding time against rain-labs.atlassian.net; pinned per BLOCK_6_PLAN.md
// decision B's instance-drift follow-up. Other Atlassian Cloud
// instances can have different IDs (custom workflow imports,
// instance-age artifacts); Block 9 polish: per-instance discovery.
const SPRINT_FIELD_ID = 'customfield_10020';
const STORY_POINTS_FIELD_ID = 'customfield_10016';

const ISSUE_FIELDS = [
  'summary', 'description', 'status', 'assignee', 'reporter',
  'priority', 'issuetype', 'labels', 'created', 'updated',
  SPRINT_FIELD_ID, STORY_POINTS_FIELD_ID,
].join(',');

// E1 pagination cap: 5 pages × 100 results = 500 issues per sync run.
const SEARCH_PAGE_SIZE = 100;
const SEARCH_MAX_PAGES = 5;
const BOARD_PAGE_SIZE = 50;
const SPRINT_PAGE_SIZE = 50;
// Safety ceilings for sprint sync (sprints are O(10) per project; these
// are way above realistic numbers, just guards against runaway pagination).
const MAX_BOARDS_PER_PROJECT = 50;
const MAX_SPRINTS_PER_BOARD = 200;

// E2 rate-limit retry: at most one retry per request; cap retry-after
// at 60s so a long Atlassian outage doesn't pin the Worker isolate.
const MAX_RETRY_AFTER_SECONDS = 60;

const METADATA = Object.freeze({
  source: 'jira',
  displayName: 'Jira',
  authKind: 'token',
  description: 'Atlassian Jira (Cloud) — issues, sprints, statuses. API token auth.',
});

class JiraApiError extends Error {
  constructor(message, { status, body } = {}) {
    super(message);
    this.name = 'JiraApiError';
    this.status = status ?? null;
    this.responseBodySnippet = body ? String(body).slice(0, 200) : null;
  }
}

// ---------------------------------------------------------------------------
// Input validation (decision N: hostname-only site_url; RFC 5322-ish email;
// non-empty api_token). Validation errors do NOT include the api_token.
// ---------------------------------------------------------------------------

function validateSiteUrl(siteUrl) {
  if (typeof siteUrl !== 'string' || siteUrl.length === 0) {
    throw new Error('site_url required');
  }
  if (siteUrl.includes('/') || siteUrl.includes(':') || siteUrl.includes(' ')) {
    throw new Error('site_url must be hostname-only (e.g. mycompany.atlassian.net)');
  }
  if (!siteUrl.endsWith('.atlassian.net')) {
    throw new Error('site_url must be an *.atlassian.net Atlassian Cloud host');
  }
  return siteUrl.toLowerCase();
}

function validateEmail(email) {
  if (typeof email !== 'string' || email.length === 0) {
    throw new Error('account_email required');
  }
  if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) {
    throw new Error('account_email malformed');
  }
  return email;
}

function validateApiToken(apiToken) {
  if (typeof apiToken !== 'string' || apiToken.length === 0) {
    throw new Error('api_token required');
  }
  return apiToken;
}

// ---------------------------------------------------------------------------
// Atlassian REST helpers (decision B subset — commit 2 uses /myself only).
// ---------------------------------------------------------------------------

function basicAuthHeader(email, apiToken) {
  return 'Basic ' + btoa(`${email}:${apiToken}`);
}

async function jiraGet(siteUrl, path, email, apiToken, _alreadyRetried = false) {
  const url = `https://${siteUrl}${path}`;
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Authorization': basicAuthHeader(email, apiToken),
      'Accept': 'application/json',
      'User-Agent': ATLASSIAN_USER_AGENT,
    },
  });

  // E2: rate-limit retry-once. On 429 with parseable Retry-After within
  // the cap, sleep + retry the same request. Second 429 → propagate as
  // JiraApiError(status=429); _doSync's catch path collapses to abort
  // the sync_run with status='failed' + detail.reason='rate_limited'.
  if (response.status === 429 && !_alreadyRetried) {
    const retryAfterRaw = response.headers.get('Retry-After');
    const retryAfter = parseInt(retryAfterRaw ?? '', 10);
    if (
      Number.isFinite(retryAfter) &&
      retryAfter > 0 &&
      retryAfter <= MAX_RETRY_AFTER_SECONDS
    ) {
      await new Promise((r) => setTimeout(r, retryAfter * 1000));
      return jiraGet(siteUrl, path, email, apiToken, /* _alreadyRetried */ true);
    }
    // Retry-After missing / unparseable / too long → propagate as 429
    // for the caller to handle; we don't sleep an unbounded interval.
  }

  const text = await response.text();
  if (!response.ok) {
    throw new JiraApiError(`Atlassian ${response.status} on ${path}`, {
      status: response.status,
      body: text,
    });
  }
  try {
    return JSON.parse(text);
  } catch {
    throw new JiraApiError(`Atlassian ${response.status} returned non-JSON on ${path}`, {
      status: response.status,
      body: text,
    });
  }
}

async function fetchMyself(siteUrl, email, apiToken) {
  return jiraGet(siteUrl, `/rest/api/${ATLASSIAN_API_VERSION}/myself`, email, apiToken);
}

// ---------------------------------------------------------------------------
// listProjects — decision G's per-source endpoint helper. Called by
// /api/projects/:id/connections/:connId/jira/projects (commit 4) to populate
// the project picker modal in the Connect Jira UI (commit 9).
//
// Pagination cap: 5 pages × 50 results = 250 projects ceiling. Larger
// instances would need a paginating-picker UI (Block 9 polish).
// ---------------------------------------------------------------------------

const PROJECT_SEARCH_PAGE_SIZE = 50;
const PROJECT_SEARCH_MAX_PAGES = 5;

// ---------------------------------------------------------------------------
// ADF → plain text. Atlassian description fields are ADF (Atlassian Document
// Format) — a JSON tree of paragraph + heading + text nodes. v1.1 extracts
// plain text only; structured rendering (headings, lists, tables) is Block 9
// polish. Recursive content traversal handles paragraph + doc + heading +
// listItem + bulletList + orderedList + blockquote + (any node with a
// `content` array) — they all carry text in their leaves.
// ---------------------------------------------------------------------------

function adfToPlainText(node) {
  if (!node || typeof node !== 'object') return '';
  if (node.type === 'text' && typeof node.text === 'string') return node.text;
  if (node.type === 'hardBreak') return '\n';
  if (Array.isArray(node.content)) {
    const inner = node.content.map(adfToPlainText).join('');
    // Block-level nodes get a newline after their contents so paragraphs
    // don't run together. Inline nodes (text, hardBreak) flow as-is.
    if (node.type === 'paragraph' || node.type === 'heading' || node.type === 'listItem') {
      return inner + '\n';
    }
    return inner;
  }
  return '';
}

// ---------------------------------------------------------------------------
// Entity mappers (decision H). source_id includes the site host so the
// UNIQUE(connection_id, source_type, source_id) constraint never collides
// across instances on the same project (forward-compat for v1.2).
// ---------------------------------------------------------------------------

function mapIssueToEntity(issue, projectKey, siteUrl) {
  const fields = issue.fields || {};
  // SPRINT_FIELD_ID returns an array of sprint objects (issues can carry
  // across sprints). For v1.1 take the first listed; multi-sprint history
  // is Block 9 polish.
  const sprintArray = fields[SPRINT_FIELD_ID];
  const sprint =
    Array.isArray(sprintArray) && sprintArray.length > 0 ? sprintArray[0] : null;

  const summary = fields.summary || '';
  const descriptionText = adfToPlainText(fields.description);
  const contentText = descriptionText
    ? `${summary}\n\n${descriptionText}`.trim()
    : summary;

  const storyPointsRaw = fields[STORY_POINTS_FIELD_ID];
  const storyPoints =
    typeof storyPointsRaw === 'number' && Number.isFinite(storyPointsRaw)
      ? storyPointsRaw
      : null;

  return {
    source: 'jira',
    source_type: 'jira_issue',
    source_id: `${siteUrl}:issue:${issue.key}`,
    title: summary || issue.key,
    content_text: contentText || null,
    author_external_id: fields.reporter?.accountId || null,
    author_display_name: fields.reporter?.displayName || null,
    source_created_at: fields.created || null,
    source_updated_at: fields.updated || null,
    source_url: `https://${siteUrl}/browse/${issue.key}`,
    metadata: {
      issue_key: issue.key,
      jira_project_key: projectKey,
      status: fields.status?.name || null,
      status_category: fields.status?.statusCategory?.key || null,
      issue_type: fields.issuetype?.name || null,
      assignee_display_name: fields.assignee?.displayName || null,
      assignee_external_id: fields.assignee?.accountId || null,
      reporter_display_name: fields.reporter?.displayName || null,
      reporter_external_id: fields.reporter?.accountId || null,
      priority: fields.priority?.name || null,
      sprint_id: sprint?.id ?? null,
      sprint_name: sprint?.name || null,
      story_points: storyPoints,
      labels: Array.isArray(fields.labels) ? fields.labels : [],
    },
    raw: issue,
  };
}

function mapSprintToEntity(sprint, boardId, projectKey, siteUrl) {
  // Sprint URL pinned at commit 5 coding time per BLOCK_6_PLAN.md decision H.
  // Verified shape against rain-labs.atlassian.net's project boards. If a
  // future Atlassian UI rev breaks this format, mapSprintToEntity is the
  // single point of update.
  const sourceUrl = `https://${siteUrl}/jira/software/projects/${projectKey}/boards/${boardId}?sprint=${sprint.id}`;
  const name = sprint.name || `Sprint ${sprint.id}`;
  const goal = typeof sprint.goal === 'string' ? sprint.goal.trim() : '';

  return {
    source: 'jira',
    source_type: 'jira_sprint',
    source_id: `${siteUrl}:sprint:${sprint.id}`,
    title: name,
    content_text: goal ? `${name}\n\n${goal}` : name,
    author_external_id: null,
    author_display_name: null,
    source_created_at: sprint.startDate || null,
    source_updated_at:
      sprint.completeDate || sprint.endDate || sprint.startDate || null,
    source_url: sourceUrl,
    metadata: {
      sprint_id: sprint.id,
      board_id: boardId,
      sprint_name: name,
      state: sprint.state || null,
      start_date: sprint.startDate || null,
      end_date: sprint.endDate || null,
      complete_date: sprint.completeDate || null,
      goal: goal || null,
      jira_project_key: projectKey,
    },
    raw: sprint,
  };
}

// ---------------------------------------------------------------------------
// Sync helpers — Atlassian REST endpoints used by _doSync (decision B).
// ---------------------------------------------------------------------------

async function listBoardsForProject(siteUrl, email, apiToken, projectKey) {
  const collected = [];
  let startAt = 0;
  while (collected.length < MAX_BOARDS_PER_PROJECT) {
    const path =
      `/rest/agile/${ATLASSIAN_AGILE_API_VERSION}/board` +
      `?projectKeyOrId=${encodeURIComponent(projectKey)}` +
      `&startAt=${startAt}&maxResults=${BOARD_PAGE_SIZE}`;
    const response = await jiraGet(siteUrl, path, email, apiToken);
    const values = Array.isArray(response.values) ? response.values : [];
    for (const board of values) {
      if (board && (typeof board.id === 'number' || typeof board.id === 'string')) {
        collected.push({
          id: board.id,
          name: board.name || `Board ${board.id}`,
        });
      }
    }
    if (response.isLast === true || values.length < BOARD_PAGE_SIZE) break;
    startAt += values.length;
  }
  return collected;
}

async function listSprintsForBoard(siteUrl, email, apiToken, boardId) {
  const collected = [];
  let startAt = 0;
  while (collected.length < MAX_SPRINTS_PER_BOARD) {
    const path =
      `/rest/agile/${ATLASSIAN_AGILE_API_VERSION}/board/${boardId}/sprint` +
      `?state=active,closed,future` +
      `&startAt=${startAt}&maxResults=${SPRINT_PAGE_SIZE}`;
    let response;
    try {
      response = await jiraGet(siteUrl, path, email, apiToken);
    } catch (err) {
      // Kanban boards (and some other board types) don't support sprints
      // and return 400 from this endpoint. Treat as "no sprints" and
      // continue — not a sync-aborting error.
      if (err instanceof JiraApiError && err.status === 400) return collected;
      throw err;
    }
    const values = Array.isArray(response.values) ? response.values : [];
    collected.push(...values);
    if (response.isLast === true || values.length < SPRINT_PAGE_SIZE) break;
    startAt += values.length;
  }
  return collected;
}

// /rest/api/3/search was deprecated by Atlassian in April 2025 and now
// returns 410 Gone. Replaced by /rest/api/3/search/jql which uses
// cursor-based pagination via `nextPageToken` instead of `startAt`.
// Response shape: { issues: [...], nextPageToken?: string, isLast?: bool }.
// Pass `nextPageToken` from the previous response to fetch the next page;
// absence of `nextPageToken` (or `isLast: true`) signals end-of-results.
async function searchIssues(siteUrl, email, apiToken, jql, nextPageToken) {
  const params = new URLSearchParams({
    jql,
    maxResults: String(SEARCH_PAGE_SIZE),
    fields: ISSUE_FIELDS,
  });
  if (nextPageToken) {
    params.set('nextPageToken', nextPageToken);
  }
  const path = `/rest/api/${ATLASSIAN_API_VERSION}/search/jql?${params.toString()}`;
  return jiraGet(siteUrl, path, email, apiToken);
}

// ---------------------------------------------------------------------------
// sweepMissingEmbeddings — connector-scoped catch-up for entities written
// without embeddings (writeEntityWithEmbedding swallows retryable errors).
// Mirrors slack.js's sweep verbatim except for the source filter (none —
// the LEFT JOIN already scopes by entity_id / connection_id).
//
// Block 7 polish candidate: move this helper into _shared/entity_writer.js
// once Monday connector arrives and we have a third call site.
// ---------------------------------------------------------------------------

async function sweepMissingEmbeddings(env, sql, connection) {
  const rows = await sql`
    SELECT e.id, e.content_text, e.metadata
      FROM entities e
      LEFT JOIN entity_embeddings ee
        ON ee.entity_id = e.id
       AND ee.model = ${EMBEDDING_MODEL_ID}
       AND ee.chunk_index = 0
     WHERE e.connection_id = ${connection.id}
       AND ee.id IS NULL
       AND e.content_text IS NOT NULL
       AND length(trim(e.content_text)) > 0
     ORDER BY e.created_at DESC
     LIMIT 50
  `;

  for (const row of rows) {
    try {
      await embedEntityRow(
        env,
        sql,
        connection.project_id,
        connection.id,
        row.id,
        { content_text: row.content_text, metadata: row.metadata }
      );
    } catch (err) {
      console.warn(JSON.stringify({
        level: 'warn',
        event: 'embedding_sweep_row_failed',
        connection_id: connection.id,
        entity_id: row.id,
        error: err && err.message ? String(err.message).slice(0, 200) : 'unknown',
      }));
    }
  }
}

// ---------------------------------------------------------------------------
// _doSync — shared sync core. Handles selected_project_key inert detection
// (decision D + L), credential decrypt, sprint refresh, paginated issue
// search, embed-on-write, sweep, cap detection.
//
// options.cursor: ISO 8601 string or null. When set, JQL filters issues
// updated >= cursor (decision O). When null, full backfill (commit 5
// always passes null; commit 6 wires incrementalSync to pass the
// connection's last_sync_cursor).
// ---------------------------------------------------------------------------

async function _doSync(ctx, connection, options = {}) {
  const cursor = options.cursor || null;

  // Decision D + L: inert sync if no project picked.
  const meta = connection.credential_metadata || {};
  const selectedProjectKey = meta.selected_project_key;
  if (!selectedProjectKey || typeof selectedProjectKey !== 'string') {
    return {
      records_inserted: 0,
      records_updated: 0,
      records_skipped: 0,
      detail: {
        inert: true,
        reason: 'no project selected',
      },
    };
  }

  // Decrypt credentials. plaintext lives only on the call stack from
  // here through Atlassian API calls; never logged, never persisted raw.
  const aad = aadFor(connection);
  const credsJson = await decrypt(ctx.env, connection, aad);
  const creds = JSON.parse(credsJson);

  let inserted = 0;
  let updated = 0;
  const skipped = 0;
  let latestUpdatedSeen = cursor;

  // Step 1: sprint refresh (always full — sprints are O(10) per project,
  // not worth incremental). Each board → its sprints → UPSERT each.
  // Sprint sync errors don't abort issue sync; they're logged and we
  // continue (sprints are observability-grade data, not critical-path).
  try {
    const boards = await listBoardsForProject(
      creds.site_url,
      creds.account_email,
      creds.api_token,
      selectedProjectKey
    );
    for (const board of boards) {
      const sprints = await listSprintsForBoard(
        creds.site_url,
        creds.account_email,
        creds.api_token,
        board.id
      );
      for (const sprint of sprints) {
        const entity = mapSprintToEntity(
          sprint,
          board.id,
          selectedProjectKey,
          creds.site_url
        );
        const result = await writeEntityWithEmbedding(
          ctx.env,
          ctx.sql,
          connection.project_id,
          connection.id,
          entity
        );
        if (result.inserted) inserted++;
        else updated++;
      }
    }
  } catch (err) {
    if (err instanceof JiraApiError && err.status === 429) {
      throw new Error('rate_limited_during_sprint_sync');
    }
    console.warn(JSON.stringify({
      level: 'warn',
      event: 'jira_sprint_sync_failed',
      connection_id: connection.id,
      error: err && err.message ? String(err.message).slice(0, 200) : 'unknown',
    }));
    // Continue to issue sync.
  }

  // Step 2: issue search. JQL pinned at decision E + O. Always order
  // by updated ASC so cursor advances monotonically; ties at exact
  // millisecond are absorbed by the UPSERT idempotency.
  let jql = `project = "${selectedProjectKey}"`;
  if (cursor) {
    // Atlassian JQL accepts ISO 8601 timestamp strings in quotes.
    // The >= comparison + UPSERT idempotency handle the boundary safely
    // (one redundant fetch per sync, no missed records).
    jql += ` AND updated >= "${cursor}"`;
  }
  jql += ' ORDER BY updated ASC';

  // /search/jql uses cursor-based pagination via `nextPageToken`. Pass
  // null on the first page; subsequent pages thread the previous response's
  // nextPageToken. End-of-results signal: response.isLast === true OR
  // response.nextPageToken absent OR issues.length < SEARCH_PAGE_SIZE.
  let nextPageToken = null;
  let pages = 0;
  let lastPageWasFull = false;
  let hasMorePages = false;

  while (pages < SEARCH_MAX_PAGES) {
    pages += 1;
    let response;
    try {
      response = await searchIssues(
        creds.site_url,
        creds.account_email,
        creds.api_token,
        jql,
        nextPageToken
      );
    } catch (err) {
      if (err instanceof JiraApiError && err.status === 429) {
        throw new Error('rate_limited');
      }
      throw err;
    }

    const issues = Array.isArray(response.issues) ? response.issues : [];
    lastPageWasFull = issues.length === SEARCH_PAGE_SIZE;

    for (const issue of issues) {
      const entity = mapIssueToEntity(issue, selectedProjectKey, creds.site_url);
      // Track max(updated) for cursor advancement (decision O).
      if (
        entity.source_updated_at &&
        (!latestUpdatedSeen || entity.source_updated_at > latestUpdatedSeen)
      ) {
        latestUpdatedSeen = entity.source_updated_at;
      }
      const result = await writeEntityWithEmbedding(
        ctx.env,
        ctx.sql,
        connection.project_id,
        connection.id,
        entity
      );
      if (result.inserted) inserted++;
      else updated++;
    }

    // End-of-results: explicit isLast OR no nextPageToken OR partial page.
    hasMorePages =
      response.isLast !== true &&
      typeof response.nextPageToken === 'string' &&
      response.nextPageToken.length > 0 &&
      lastPageWasFull;
    if (!hasMorePages) break;
    nextPageToken = response.nextPageToken;
  }

  // E1 cap-hit signal: hit MAX_PAGES with more pages still available.
  // Subsequent sync runs catch up via the cursor (decision E1; v1.1
  // known limitation per E1's note: no nightly cron until Block 9, so
  // admin must manually re-sync).
  const capHit = pages >= SEARCH_MAX_PAGES && hasMorePages;

  /** @type {import('./types.js').SyncResult} */
  const result = {
    records_inserted: inserted,
    records_updated: updated,
    records_skipped: skipped,
    cursor_after: latestUpdatedSeen || null,
  };

  if (capHit) {
    result.detail = {
      cap_hit: true,
      cap_pages: SEARCH_MAX_PAGES,
      cap_records: SEARCH_PAGE_SIZE * SEARCH_MAX_PAGES,
      latest_synced_updated_ts: latestUpdatedSeen,
    };
  }

  // Sweep — catch any missing embeddings from this sync (or prior
  // syncs that failed mid-embed). Errors logged; not sync-aborting.
  try {
    await sweepMissingEmbeddings(ctx.env, ctx.sql, connection);
  } catch (err) {
    console.warn(JSON.stringify({
      level: 'warn',
      event: 'embedding_sweep_failed',
      connection_id: connection.id,
      error: err && err.message ? String(err.message).slice(0, 200) : 'unknown',
    }));
  }

  return result;
}

/**
 * List Jira projects accessible to the connection's API token.
 *
 * Decrypts credentials internally (Block 3 decision L); handler never sees
 * plaintext. Returns array of { key, name } sorted by Atlassian's response
 * order. Atlassian's project_search response shape:
 *   { values: [{ id, key, name, ... }], isLast: bool, startAt, total }
 *
 * @param {import('./types.js').ConnectorCtx} ctx
 * @param {import('./types.js').ConnectionRow} connection
 * @returns {Promise<Array<{ key: string, name: string }>>}
 */
export async function listProjects(ctx, connection) {
  const aad = aadFor(connection);
  const credsJson = await decrypt(ctx.env, connection, aad);
  const creds = JSON.parse(credsJson);

  const collected = [];
  let startAt = 0;
  let pages = 0;

  while (pages < PROJECT_SEARCH_MAX_PAGES) {
    pages += 1;
    const path = `/rest/api/${ATLASSIAN_API_VERSION}/project/search?startAt=${startAt}&maxResults=${PROJECT_SEARCH_PAGE_SIZE}`;
    const response = await jiraGet(creds.site_url, path, creds.account_email, creds.api_token);

    const values = Array.isArray(response.values) ? response.values : [];
    for (const project of values) {
      if (typeof project.key === 'string' && typeof project.name === 'string') {
        collected.push({ key: project.key, name: project.name });
      }
    }

    if (response.isLast === true || values.length < PROJECT_SEARCH_PAGE_SIZE) {
      break;
    }
    startAt += values.length;
  }

  return collected;
}

// ---------------------------------------------------------------------------
// Connector export (decision N: completeAuth is the canonical entry; the
// startAuth method exists only to satisfy the Connector interface).
// ---------------------------------------------------------------------------

/** @type {import('./types.js').Connector} */
export const jira = {
  getMetadata() {
    return METADATA;
  },

  // Jira uses API token auth; the OAuth-shaped startAuth/authUrl flow
  // doesn't apply. Connections are created via the bespoke
  // POST /api/connectors/jira/auth/save endpoint (decision N), which
  // calls completeAuth directly. startAuth exists only to satisfy the
  // Connector interface contract; reaching this throw means a caller
  // tried to use the OAuth path on Jira (Block 4's POST /connections
  // refactor will route Jira to /auth/save instead).
  async startAuth(_ctx) {
    throw new Error(
      'Jira uses API tokens; POST credentials to /api/connectors/jira/auth/save'
    );
  },

  // params shape: { site_url, account_email, api_token }.
  // Validates inputs, calls Atlassian /myself to verify credentials,
  // returns { credentials, accountInfo } per the Connector contract.
  // The handler (functions/api/connectors/jira/auth/save.js) encrypts
  // credentials before INSERTing the connections row.
  //
  // Throws Error('invalid_credentials') on Atlassian 401/403; lets
  // other errors propagate so the handler can collapse them.
  async completeAuth(_ctx, params) {
    const siteUrl = validateSiteUrl(params?.site_url);
    const email = validateEmail(params?.account_email);
    const apiToken = validateApiToken(params?.api_token);

    let myself;
    try {
      myself = await fetchMyself(siteUrl, email, apiToken);
    } catch (err) {
      if (
        err instanceof JiraApiError &&
        (err.status === 401 || err.status === 403)
      ) {
        throw new Error('invalid_credentials');
      }
      throw err;
    }

    return {
      credentials: {
        site_url: siteUrl,
        account_email: email,
        api_token: apiToken,
      },
      accountInfo: {
        // external_account_id = lowercased site host (decision C
        // fallback path). Single connection per (project_id, 'jira',
        // site_host) at the application layer (decision F).
        id: siteUrl,
        atlassian_account_id: myself.accountId || null,
        atlassian_display_name: myself.displayName || null,
        atlassian_email: myself.emailAddress || null,
        site_url: siteUrl,
        account_email: email,
      },
    };
  },

  // No-op; Atlassian API tokens are long-lived and not platform-rotated.
  // Per decision A (token rotation deferred to v1.2 OAuth).
  async refreshAuth(_ctx, credentials) {
    return credentials;
  },

  async testConnection(ctx, connection) {
    const aad = aadFor(connection);
    let credsJson;
    try {
      credsJson = await decrypt(ctx.env, connection, aad);
    } catch {
      return { ok: false, error: 'decrypt_failed' };
    }
    let creds;
    try {
      creds = JSON.parse(credsJson);
    } catch {
      return { ok: false, error: 'credentials_malformed' };
    }
    try {
      const myself = await fetchMyself(creds.site_url, creds.account_email, creds.api_token);
      return {
        ok: true,
        accountInfo: {
          id: creds.site_url,
          atlassian_account_id: myself.accountId || null,
          atlassian_display_name: myself.displayName || null,
        },
      };
    } catch (err) {
      if (err instanceof JiraApiError && (err.status === 401 || err.status === 403)) {
        return { ok: false, error: 'invalid_credentials' };
      }
      return { ok: false, error: 'connection_failed' };
    }
  },

  // Full backfill — pulls all issues for the connection's
  // selected_project_key from Atlassian, plus all sprints across all
  // boards for that project. No date filter (cursor=null). E1
  // pagination cap = 5 pages × 100 = 500 issues per sync run; larger
  // backlogs require multiple manual sync clicks (decision E1's v1.1
  // known limitation — Block 9 nightly cron mitigates).
  async fullSync(ctx, connection) {
    return _doSync(ctx, connection, { cursor: null });
  },

  // Cursor-based incremental sync (decision O). Reads
  // connection.last_sync_cursor (ISO 8601 string seeded by the
  // previous sync's cursor_after); _doSync builds JQL with
  // `AND updated >= "<cursor>"`. First incremental on a connection
  // with no prior cursor falls through to full backfill (cursor=null).
  //
  // Boundary safety: cursor is set to max(updated), not max(updated)+1ms.
  // JQL >= plus the entity UPSERT idempotency (UNIQUE on
  // connection_id + source_type + source_id) absorbs one duplicate
  // fetch per sync. Atlassian's JQL doesn't expose milliseconds
  // reliably, so the simpler >= + idempotent UPSERT is safer than
  // attempting to bump the cursor by 1ms (which risks losing issues
  // whose `updated` matches the cursor exactly).
  async incrementalSync(ctx, connection) {
    const cursor =
      typeof connection.last_sync_cursor === 'string' &&
      connection.last_sync_cursor.length > 0
        ? connection.last_sync_cursor
        : null;
    return _doSync(ctx, connection, { cursor });
  },
};
