// functions/_lib/connectors/jira.js
// =========================================================================
// SECURITY-CARVE-OUT: do not edit in auto mode
//
// Jira connector. Implements decisions A (API token, no OAuth),
// B (5 REST endpoints; commit 2 only uses /myself), C (envelope
// encryption reuse), D (single project per connection — picker in
// commit 9), E + E1 + E2 + E3 (sync model — commits 5/6 only;
// commit 2 ships stubs that return inert SyncResult), F (single
// connection per Jira instance per project — enforced at the save
// endpoint in commit 3, not here), G (project listing endpoint —
// commit 4), H (entity mapping — commits 5/6), I/I1/I2/I3/I4 (tools
// — commit 7), J (jira_issues view — commit 4), K (system prompt —
// commit 8), L (connect UI — commit 9), N (bespoke save endpoint —
// commit 3), O (cursor format — commit 6) from BLOCK_6_PLAN.md.
//
// AUTH MODEL (decision A)
// -----------------------
// authKind = 'token'. Per-user Atlassian API token, generated by the
// admin at https://id.atlassian.com/manage-profile/security/api-tokens.
// Authentication on outbound calls is HTTP Basic:
//   Authorization: Basic ${base64(email + ':' + apiToken)}
// No OAuth callback, no refresh tokens, no consent screen. Connections
// are created via POST /api/connectors/jira/auth/save (decision N),
// which calls completeAuth directly. startAuth throws to satisfy the
// Connector interface contract — it should never be reached for Jira.
//
// CREDENTIAL SHAPE
// ----------------
// Encrypted blob: { site_url, account_email, api_token } as JSON.
// credential_metadata (non-secret, dashboard-visible to admins):
//   { site_url, account_email, atlassian_account_id,
//     selected_project_key?, selected_project_name? }
// Note credential_metadata MUST NOT contain api_token (verified by
// S21 in the verification matrix).
//
// EXTERNAL_ACCOUNT_ID (decision C, fallback path)
// -----------------------------------------------
// connections.external_account_id stores the lowercased site host
// (e.g. 'mycompany.atlassian.net'). Decision C originally preferred
// the Atlassian site cloud ID from /_edge/tenant_info, but v1.1 takes
// the simpler fallback path: lowercased site host is unambiguous,
// requires zero extra API calls, and satisfies decision F's UNIQUE-
// constraint slot for "single connection per Jira instance per
// project." Block 9 polish: switch to cloud ID if multi-region or
// vanity-domain instances surface.
//
// SECURITY (mirrors slack.js)
// ---------------------------
// Error strings MUST NOT include any byte of the plaintext API token,
// not even truncated. Atlassian's error responses on 401/403 don't
// echo the token, so jiraGet's response body snippet is safe to log;
// validation errors don't include the token either. NEVER concatenate
// creds.api_token into any error or log line.
//
// COMMITS 5/6 ADDITIONS (deferred from commit 2)
// ----------------------------------------------
// fullSync, incrementalSync — currently stubbed to return inert
// SyncResult ({inert:true, reason:'not implemented yet'}). The L
// inert-sync rule (Block 4) means /sync calls against Jira
// connections in the commit-2-through-commit-4 window won't poison
// connections.last_sync_at. Real implementations land in commits 5
// (fullSync via /rest/api/3/search + agile API) and 6 (incremental
// via JQL `updated >= last_sync_cursor`).
//
// E3 NO WEBHOOK FOR V1.1
// ----------------------
// Jira webhooks require admin-level configuration in the Atlassian
// instance settings (per-instance, not per-user). API-token-auth
// users cannot register webhooks programmatically. v1.1 ships
// without handleWebhook; admin uses the manual "Sync now" button +
// Block 9's nightly cron. Per decision E3.
// =========================================================================

import { aadFor, decrypt } from '../crypto.js';

const ATLASSIAN_API_VERSION = '3';
const ATLASSIAN_USER_AGENT = 'elinno-agent/1.1';

const METADATA = Object.freeze({
  source: 'jira',
  displayName: 'Jira',
  authKind: 'token',
  description: 'Atlassian Jira (Cloud) — issues, sprints, statuses. API token auth.',
});

class JiraApiError extends Error {
  constructor(message, { status, body } = {}) {
    super(message);
    this.name = 'JiraApiError';
    this.status = status ?? null;
    this.responseBodySnippet = body ? String(body).slice(0, 200) : null;
  }
}

// ---------------------------------------------------------------------------
// Input validation (decision N: hostname-only site_url; RFC 5322-ish email;
// non-empty api_token). Validation errors do NOT include the api_token.
// ---------------------------------------------------------------------------

function validateSiteUrl(siteUrl) {
  if (typeof siteUrl !== 'string' || siteUrl.length === 0) {
    throw new Error('site_url required');
  }
  if (siteUrl.includes('/') || siteUrl.includes(':') || siteUrl.includes(' ')) {
    throw new Error('site_url must be hostname-only (e.g. mycompany.atlassian.net)');
  }
  if (!siteUrl.endsWith('.atlassian.net')) {
    throw new Error('site_url must be an *.atlassian.net Atlassian Cloud host');
  }
  return siteUrl.toLowerCase();
}

function validateEmail(email) {
  if (typeof email !== 'string' || email.length === 0) {
    throw new Error('account_email required');
  }
  if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) {
    throw new Error('account_email malformed');
  }
  return email;
}

function validateApiToken(apiToken) {
  if (typeof apiToken !== 'string' || apiToken.length === 0) {
    throw new Error('api_token required');
  }
  return apiToken;
}

// ---------------------------------------------------------------------------
// Atlassian REST helpers (decision B subset — commit 2 uses /myself only).
// ---------------------------------------------------------------------------

function basicAuthHeader(email, apiToken) {
  return 'Basic ' + btoa(`${email}:${apiToken}`);
}

async function jiraGet(siteUrl, path, email, apiToken) {
  const url = `https://${siteUrl}${path}`;
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Authorization': basicAuthHeader(email, apiToken),
      'Accept': 'application/json',
      'User-Agent': ATLASSIAN_USER_AGENT,
    },
  });
  const text = await response.text();
  if (!response.ok) {
    throw new JiraApiError(`Atlassian ${response.status} on ${path}`, {
      status: response.status,
      body: text,
    });
  }
  try {
    return JSON.parse(text);
  } catch {
    throw new JiraApiError(`Atlassian ${response.status} returned non-JSON on ${path}`, {
      status: response.status,
      body: text,
    });
  }
}

async function fetchMyself(siteUrl, email, apiToken) {
  return jiraGet(siteUrl, `/rest/api/${ATLASSIAN_API_VERSION}/myself`, email, apiToken);
}

// ---------------------------------------------------------------------------
// listProjects — decision G's per-source endpoint helper. Called by
// /api/projects/:id/connections/:connId/jira/projects (commit 4) to populate
// the project picker modal in the Connect Jira UI (commit 9).
//
// Pagination cap: 5 pages × 50 results = 250 projects ceiling. Larger
// instances would need a paginating-picker UI (Block 9 polish).
// ---------------------------------------------------------------------------

const PROJECT_SEARCH_PAGE_SIZE = 50;
const PROJECT_SEARCH_MAX_PAGES = 5;

/**
 * List Jira projects accessible to the connection's API token.
 *
 * Decrypts credentials internally (Block 3 decision L); handler never sees
 * plaintext. Returns array of { key, name } sorted by Atlassian's response
 * order. Atlassian's project_search response shape:
 *   { values: [{ id, key, name, ... }], isLast: bool, startAt, total }
 *
 * @param {import('./types.js').ConnectorCtx} ctx
 * @param {import('./types.js').ConnectionRow} connection
 * @returns {Promise<Array<{ key: string, name: string }>>}
 */
export async function listProjects(ctx, connection) {
  const aad = aadFor(connection);
  const credsJson = await decrypt(ctx.env, connection, aad);
  const creds = JSON.parse(credsJson);

  const collected = [];
  let startAt = 0;
  let pages = 0;

  while (pages < PROJECT_SEARCH_MAX_PAGES) {
    pages += 1;
    const path = `/rest/api/${ATLASSIAN_API_VERSION}/project/search?startAt=${startAt}&maxResults=${PROJECT_SEARCH_PAGE_SIZE}`;
    const response = await jiraGet(creds.site_url, path, creds.account_email, creds.api_token);

    const values = Array.isArray(response.values) ? response.values : [];
    for (const project of values) {
      if (typeof project.key === 'string' && typeof project.name === 'string') {
        collected.push({ key: project.key, name: project.name });
      }
    }

    if (response.isLast === true || values.length < PROJECT_SEARCH_PAGE_SIZE) {
      break;
    }
    startAt += values.length;
  }

  return collected;
}

// ---------------------------------------------------------------------------
// Connector export (decision N: completeAuth is the canonical entry; the
// startAuth method exists only to satisfy the Connector interface).
// ---------------------------------------------------------------------------

/** @type {import('./types.js').Connector} */
export const jira = {
  getMetadata() {
    return METADATA;
  },

  // Jira uses API token auth; the OAuth-shaped startAuth/authUrl flow
  // doesn't apply. Connections are created via the bespoke
  // POST /api/connectors/jira/auth/save endpoint (decision N), which
  // calls completeAuth directly. startAuth exists only to satisfy the
  // Connector interface contract; reaching this throw means a caller
  // tried to use the OAuth path on Jira (Block 4's POST /connections
  // refactor will route Jira to /auth/save instead).
  async startAuth(_ctx) {
    throw new Error(
      'Jira uses API tokens; POST credentials to /api/connectors/jira/auth/save'
    );
  },

  // params shape: { site_url, account_email, api_token }.
  // Validates inputs, calls Atlassian /myself to verify credentials,
  // returns { credentials, accountInfo } per the Connector contract.
  // The handler (functions/api/connectors/jira/auth/save.js) encrypts
  // credentials before INSERTing the connections row.
  //
  // Throws Error('invalid_credentials') on Atlassian 401/403; lets
  // other errors propagate so the handler can collapse them.
  async completeAuth(_ctx, params) {
    const siteUrl = validateSiteUrl(params?.site_url);
    const email = validateEmail(params?.account_email);
    const apiToken = validateApiToken(params?.api_token);

    let myself;
    try {
      myself = await fetchMyself(siteUrl, email, apiToken);
    } catch (err) {
      if (
        err instanceof JiraApiError &&
        (err.status === 401 || err.status === 403)
      ) {
        throw new Error('invalid_credentials');
      }
      throw err;
    }

    return {
      credentials: {
        site_url: siteUrl,
        account_email: email,
        api_token: apiToken,
      },
      accountInfo: {
        // external_account_id = lowercased site host (decision C
        // fallback path). Single connection per (project_id, 'jira',
        // site_host) at the application layer (decision F).
        id: siteUrl,
        atlassian_account_id: myself.accountId || null,
        atlassian_display_name: myself.displayName || null,
        atlassian_email: myself.emailAddress || null,
        site_url: siteUrl,
        account_email: email,
      },
    };
  },

  // No-op; Atlassian API tokens are long-lived and not platform-rotated.
  // Per decision A (token rotation deferred to v1.2 OAuth).
  async refreshAuth(_ctx, credentials) {
    return credentials;
  },

  async testConnection(ctx, connection) {
    const aad = aadFor(connection);
    let credsJson;
    try {
      credsJson = await decrypt(ctx.env, connection, aad);
    } catch {
      return { ok: false, error: 'decrypt_failed' };
    }
    let creds;
    try {
      creds = JSON.parse(credsJson);
    } catch {
      return { ok: false, error: 'credentials_malformed' };
    }
    try {
      const myself = await fetchMyself(creds.site_url, creds.account_email, creds.api_token);
      return {
        ok: true,
        accountInfo: {
          id: creds.site_url,
          atlassian_account_id: myself.accountId || null,
          atlassian_display_name: myself.displayName || null,
        },
      };
    } catch (err) {
      if (err instanceof JiraApiError && (err.status === 401 || err.status === 403)) {
        return { ok: false, error: 'invalid_credentials' };
      }
      return { ok: false, error: 'connection_failed' };
    }
  },

  // Stubbed for commit 2. Real implementation lands in commit 5.
  // Returns inert SyncResult (detail.inert: true) so the existing
  // /sync endpoint doesn't 500 if called against a Jira connection
  // in the commit-2-through-commit-4 window — and so connections.
  // last_sync_at is NOT advanced (per Block 4 decision L).
  async fullSync(_ctx, _connection) {
    return {
      records_inserted: 0,
      records_updated: 0,
      records_skipped: 0,
      detail: { inert: true, reason: 'jira fullSync not implemented yet (commit 5)' },
    };
  },

  async incrementalSync(_ctx, _connection) {
    return {
      records_inserted: 0,
      records_updated: 0,
      records_skipped: 0,
      detail: { inert: true, reason: 'jira incrementalSync not implemented yet (commit 6)' },
    };
  },
};
